name: Fosdem-21
on:
  schedule:
    - cron: '0 0 1 */1 *' # Every month
  workflow_dispatch: # Allow manual triggering

env:
  REPO: gianlu33/reactive-base:fosdem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
      with:
        ref: fosdem-21
    -
      name: Build
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t ${{ env.REPO }} .
        docker push ${{ env.REPO }}
        docker logout
